/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CelebrationRouteImport } from './routes/celebration'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminRsvpsRouteImport } from './routes/admin.rsvps'
import { Route as CheckinCodeRouteImport } from './routes/checkin.$code'
import { Route as ApiPublicQrCodeRouteImport } from './routes/api/public/qr.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationRoute = CelebrationRouteImport.update({
  id: '/celebration',
  path: '/celebration',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRsvpsRoute = AdminRsvpsRouteImport.update({
  id: '/rsvps',
  path: '/rsvps',
  getParentRoute: () => AdminRoute,
} as any)
const CheckinCodeRoute = CheckinCodeRouteImport.update({
  id: '/checkin/$code',
  path: '/checkin/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQrCodeRoute = ApiPublicQrCodeRouteImport.update({
  id: '/api/public/qr/$code',
  path: '/api/public/qr/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/celebration': typeof CelebrationRoute
  '/gifts': typeof GiftsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/rsvps': typeof AdminRsvpsRoute
  '/checkin/$code': typeof CheckinCodeRoute
  '/api/public/qr/$code': typeof ApiPublicQrCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/celebration': typeof CelebrationRoute
  '/gifts': typeof GiftsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/rsvps': typeof AdminRsvpsRoute
  '/checkin/$code': typeof CheckinCodeRoute
  '/api/public/qr/$code': typeof ApiPublicQrCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/celebration': typeof CelebrationRoute
  '/gifts': typeof GiftsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/rsvps': typeof AdminRsvpsRoute
  '/checkin/$code': typeof CheckinCodeRoute
  '/api/public/qr/$code': typeof ApiPublicQrCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/celebration'
    | '/gifts'
    | '/reset-password'
    | '/admin/checkin'
    | '/admin/rsvps'
    | '/checkin/$code'
    | '/api/public/qr/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/celebration'
    | '/gifts'
    | '/reset-password'
    | '/admin/checkin'
    | '/admin/rsvps'
    | '/checkin/$code'
    | '/api/public/qr/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/celebration'
    | '/gifts'
    | '/reset-password'
    | '/admin/checkin'
    | '/admin/rsvps'
    | '/checkin/$code'
    | '/api/public/qr/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CelebrationRoute: typeof CelebrationRoute
  GiftsRoute: typeof GiftsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CheckinCodeRoute: typeof CheckinCodeRoute
  ApiPublicQrCodeRoute: typeof ApiPublicQrCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebration': {
      id: '/celebration'
      path: '/celebration'
      fullPath: '/celebration'
      preLoaderRoute: typeof CelebrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rsvps': {
      id: '/admin/rsvps'
      path: '/rsvps'
      fullPath: '/admin/rsvps'
      preLoaderRoute: typeof AdminRsvpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkin/$code': {
      id: '/checkin/$code'
      path: '/checkin/$code'
      fullPath: '/checkin/$code'
      preLoaderRoute: typeof CheckinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qr/$code': {
      id: '/api/public/qr/$code'
      path: '/api/public/qr/$code'
      fullPath: '/api/public/qr/$code'
      preLoaderRoute: typeof ApiPublicQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminRsvpsRoute: typeof AdminRsvpsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCheckinRoute: AdminCheckinRoute,
  AdminRsvpsRoute: AdminRsvpsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CelebrationRoute: CelebrationRoute,
  GiftsRoute: GiftsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CheckinCodeRoute: CheckinCodeRoute,
  ApiPublicQrCodeRoute: ApiPublicQrCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
